blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --------------------------------------------------
# Author:    LJ
# Email:     admin@attacker.club

# Date:      18-5-29
# Description:
# --------------------------------------------------


from django.urls import path, re_path, include
# re_path方法相当于 django1.11 url正则表达式
from . import views
from . import custom_search

# 载入视图模块

from haystack.views import SearchView

app_name = 'blog'
# 设置应用命名空间

urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.IndexView.as_view(), name="index"),

    # r正则;（）取出的内容;?P<> 里面是视图的参数名;[0-9]+数字;$结尾
    # re_path(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # re_path(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # re_path(r'^detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    re_path(r'^detail/(?P<pk>\d+).html$', views.detail, name='detail'),
    # re_path(r'^archive/$', views.archive, name='archive'),
    re_path(r'^articles/$', views.archive, name='articles'),
    # re_path(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/', views.archive, name='archive'),  # http://127.0.0.1:8000/archive/2019/1/

    re_path(r'^tag/$', views.TagView.as_view(), name='tag'),
    re_path(r'^category/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^archive/$', views.ArchiveView.as_view(), name='archive'),
    # re_path(r'^search/$', views.search, name='search'),

    # path(r'search/', include('haystack.urls'),name='search'),
    # re_path(r'search/', , name='haystack_search'),

    # re_path(r'^search/',views.MySearchView, name='haystack_search'),

    # re_path('^search/', views.MySearchView.as_view(), name='haystack_search'),

    re_path('^search/', custom_search.MySearchIndex(), name='haystack_search'),

    re_path(r'^tag/(?P<name>.*?)/$', views.tag, name='tag'),
    re_path(r'^category/(?P<pk>\d+)/$', views.category, name='category'),

    # ex: /polls/5/
    # ex: /polls/5/results/
    # ex: /polls/5/vote/
]

comments/urls.py
from django.conf.urls import re_path

from . import views

app_name = 'comments'
urlpatterns = [
    re_path(r'^comment/article/(?P<pk>\d+)/$', views.article_comment, name='article_comment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

from django.conf import settings

from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.shortcuts import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comments.urls')),
    path('', include('blog.urls',namespace='blog')), # 默认首页
    path('topic/', include('topic.urls',namespace='topic')), # 专题
    path('mdeditor/',include('mdeditor.urls')),
    # re_path(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /admin', content_type='text/plain')),

]

#http://127.0.0.1:8000/blog


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

from mdeditor.fields import MDTextField #

class Category(models.Model): #分类
    """
    继承django.db.models.Models模块
    """
    name = models.CharField(verbose_name='文章分类',max_length=100)

    class Meta:
        verbose_name_plural = "分类"
    def __str__(self):
        return self.name


class Tag(models.Model): #标签
    name = models.CharField(verbose_name='标签',max_length=100)

    class Meta:
        verbose_name_plural = "标签"
    def __str__(self):
        return self.name


class Article(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    django会自动新建自增id作为主键
    """

    status_choice = (
        (0, '原'),
        (1, '转'),
        (2, '顶'),
    )




    title = models.CharField(verbose_name='标题',max_length=70) # 标题
    body = MDTextField(verbose_name='正文',blank=True, null=True)
    #body = models.TextField(verbose_name='正文',blank=True, null=True)  # 文章正文
    digest = models.TextField(blank=True, null=True)  # 文章摘要
    status = models.SmallIntegerField(choices=status_choice, default=0, verbose_name='类型')
    publish = models.DateTimeField(verbose_name='发布时间',default=timezone.now) #发布时间
    mod_date = models.DateField(verbose_name='更新时间',auto_now=True) #更新时间

    category = models.ForeignKey(Category,verbose_name='分类', on_delete=models.CASCADE)
    #分类
    tags = models.ManyToManyField(Tag,verbose_name='标签', blank=True) #标签

    view = models.BigIntegerField(verbose_name='阅读数',default=0)  # 阅读数
    # comment = models.BigIntegerField(verbose_name='评论数',default=0)  # 评论数
    author = models.CharField(default='anonymous', verbose_name='作者', editable=False, max_length=128)
    picture = models.CharField(verbose_name='图片地址',max_length=200,blank=True,null=True) # 图片地址

    def __str__(self):
        return self.title


    def viewed(self):
        """
        增加阅读数
        :return:
        """
        self.view += 1
        self.save(update_fields=['view'])
    # def commenced(self):
    #     """
    #     增加评论数
    #     :return:
    #     """
    #     self.comment += 1
    #     self.save(update_fields=['comment'])

    def save(self, *args, **kwargs):
        """
        重写摘要
        :param args:
        :param kwargs:
        :return:
        """
        body = self.body

        # 从 body 摘取前 54 个字符赋给到 excerpt
        self.digest = body[:80]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Article, self).save(*args, **kwargs)


    class Meta:
        ordering = ['-publish']
        verbose_name_plural  = "文章"



#
# class Comment(models.Model):
#     title = models.CharField("标题", max_length=100)
#     source_id = models.CharField('文章id或source名称', max_length=25)
#     create_time = models.DateTimeField('评论时间', auto_now=True)
#     user_name = models.CharField('评论用户', max_length=25)
#     url = models.CharField('链接', max_length=100)
#     comment = models.CharField('评论内容', max_length=500)


class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name




"""
    digest = models.CharField(verbose_name='摘要',max_length=200, blank=True) # 文章摘要
    def save(self, *args, **kwargs): #复写 save 方法获取摘
        # 从 body 摘取前 54 个字符赋给到 digest
        self.digest = self.body[:54]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Article, self).save(*args, **kwargs)
"""

blog/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from blog.models import Article, Category, Tag
from  topic.models import  *


import markdown
from django.views.generic import ListView #DetailView
from django.utils.safestring import mark_safe


from comments.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# 分页模块


from django.views import View





from haystack.generic_views import SearchView
class MySearchView(SearchView):
    """My custom search view."""

    # def get_queryset(self):
    #     queryset = super(MySearchView, self).get_queryset()
    #     # further filter queryset based on some set of criteria
    #     return queryset.filter(pub_date__gte=date(2015, 1, 1))

    def get_context_data(self, *args, **kwargs):

        context = super(MySearchView, self).get_context_data(*args, **kwargs)

        tag_all = [tag for tag in Tag.objects.all()]

        # do something

        topic_indexes = {}
        topic_all = Topic.objects.all()  # 专题
        for t in topic_all:
            k = [i.pk for i in Post.objects.filter(topic=t.pk)[:1]]
            if len(k) > 0:
                topic_indexes[k[0]] = t.name


        context = locals()
        return context


# # from haystack.views import SearchView
# class MySeachView(SearchView):
#
#
#     def extra_context(self):       #重载extra_context来添加额外的context内容
#         context = super(MySeachView,self).extra_context()
#
#         tag_all = [tag for tag in Tag.objects.all()]  # tags
#
#         context = locals()
#         return context






def search(request):
    if request.user.is_authenticated:
        user_login = True



    topic_indexes = {}
    topic_all = Topic.objects.all()  # 专题
    for t in topic_all:
        k = [i.pk for i in Post.objects.filter(topic=t.pk)[:1]]
        if len(k) > 0:
            topic_indexes[k[0]] = t.name




    key = request.GET.get('key')
    error_msg = ''

    tag_all = [tag for tag in Tag.objects.all()]



    if not key:
        error_msg = "请输入关键词"
        return render(request, 'index.html', {'error_msg': error_msg})

    elif request.user.is_authenticated:  # 判断是否登录
        article_list = Article.objects.filter(title__icontains=key)
        return render(request, 'index.html', {'error_msg': error_msg,
                                              "tag_all": tag_all,
                                              "user_login": user_login,
                                              "article_list": article_list, "key": key})
    else:
        error_msg = mark_safe('''<div class="alert alert-info">
				 <button type="button" class="close" data-dismiss="alert">×</button>
				<h4>
					提示!
				</h4> <strong>搜索失败!</strong> 请先登录 ...
			</div>''')
        return render(request, 'index.html', {'error_msg': error_msg})

    # article_list = Article.objects.filter(Q(title__icontains=key) | Q(body__icontains=key))
    # 全文搜索


class IndexView(View):
    """
    cbv 基于类视图
    """
    def get(self, request):

        post_all = Article.objects.order_by('-status','-publish')# 博客所有


        topic_indexes = {}
        topic_all = Topic.objects.all() # 专题
        for t in topic_all:
            k = [i.pk for i in Post.objects.filter(topic=t.pk)[:1]]
            if len(k) >0:
                topic_indexes[k[0]] = t.name


        page = Paginator(post_all, 5)  # 将文章数分页(2)

        page_num = page.num_pages  # 分页数总数
        page_range = page.page_range  # 页码的列表数目

        page_first = page.page(1)  # 第1页的page对象
        # page_first_list = page_first.object_list  # 首页展示文章条数


        page_count = page.count  # 总数据量

        try:
            # GET请求方式，get()获取指定Key值所对应的value值
            # 获取page的值，url内输入的?page = 页码数  显示你输入的页面数目 默认为第1页
            num = request.GET.get('page', 1)
            # 获取第几页
            number = page.page(1)
        except PageNotAnInteger:
            # 如果输入的页码数不是整数，那么显示第一页数据
            number = page.page(1)
        except EmptyPage:
            number = page.page(page.num_pages)

        start = int(num)  # 当前页面数

        if page_num   > 5: # 总分页数大于5
            if start +5 > page_num:  # 你输入的值
                pageRange = range(start-4, start+1) # 大于展示按钮数量时

            else:
                pageRange = range(start, start+5)  # 显示分页按钮数量

        else:
            pageRange = page.page_range # 正常分配range(1, 4)


        currentPage = page.page(num)  # 当前页面

        currentRange = currentPage.number+1 # 显示末尾



        article_list = currentPage.object_list

        tag_all = [tag for tag in Tag.objects.all()]  # tags

        if request.user.is_authenticated:  # 登录
            user_login = True

        return render(request, 'index.html', locals())




def detail(request, pk):
    """
    博文详情
    """
    topic_indexes = {}
    topic_all = Topic.objects.all()  # 专题
    for t in topic_all:
        k = [i.pk for i in Post.objects.filter(topic=t.pk)[:1]]
        if len(k) > 0:
            topic_indexes[k[0]] = t.name




    ua = request.META.get('HTTP_USER_AGENT')
    ipaddr = request.META['REMOTE_ADDR']



    article = get_object_or_404(Article, pk=pk)
    article.viewed()  # 阅读量统计
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    article.body = md.convert(article.body.replace("\r\n", '\n'))
    toc = md.toc


    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = article.comment_set.all()



    detail_tag = Article.objects.get(pk=pk).tags.all()

    if request.user.is_authenticated:
        user_login = True

    # context = {"article": article,
    #            'form': form,
    #            "ua":ua,
    #            "ipaddr":ipaddr,
    #            'comment_list': comment_list,
    #            "source_id": article.id,
    #            'toc': md.toc }

    context = locals()
    return render(request, 'blog/detail.html', context)




def articles(request, pk):
    """
    博客列表页面
    :param request:
    :param pk:
    :return:
    """
    pk = int(pk)
    if pk:
        category_object = get_object_or_404(Category, pk=pk)
        category = category_object.name
        article_list = Article.objects.filter(category_id=pk)
    else:
        # pk为0时表示全部
        article_list = Article.objects.all()  # 获取全部文章
        category = ''
    return render(request, 'blog/articles.html', {"article_list": article_list,
                                             "category": category,
                                             })


def archive(request, year, month):
    """
    归档
    :param request:
    :param year:
    :param month:
    :return:
    """
    article_list = Article.objects.filter(publish__year=year, publish__month=month).order_by('-publish')
    return render(request, 'blog/archive.html', context={"article_list": article_list})


class TagView(View):
    model = Tag
    context_object_name = 'tags'
    template_name = 'blog/tags.html'


class CategoryView(View):
    model = Category
    context_object_name = 'categories'
    template_name = 'blog/category.html'


class ArchiveView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'blog/archive.html'


def tag(request, name):
    """
    标签
    :param request:
    :param name
    :return:
    """
    tag_all = [tag for tag in Tag.objects.all()]
    article_list = Article.objects.filter(tags__name=name)
    return render(request, 'index.html', {"article_list": article_list,
                                          "tag_all": tag_all
                                          })


def category(request, pk):
    # 记得在开始部分导入 Category 类

    topic_indexes = {}
    topic_all = Topic.objects.all()  # 专题
    for t in topic_all:
        k = [i.pk for i in Post.objects.filter(topic=t.pk)[:1]]
        if len(k) > 0:
            topic_indexes[k[0]] = t.name


    if request.user.is_authenticated:
        user_login = True

    tag_all = [tag for tag in Tag.objects.all()]

    cate = get_object_or_404(Category, pk=pk)
    post_all = Article.objects.filter(category=cate).order_by('-publish')


    page = Paginator(post_all, 9)  # 将文章数分页(2)

    page_num = page.num_pages  # 分页数总数
    page_range = page.page_range  # 页码的列表数目

    page_first = page.page(1)  # 第1页的page对象
    # page_first_list = page_first.object_list  # 首页展示文章条数

    page_count = page.count  # 总数据量

    try:
        # GET请求方式，get()获取指定Key值所对应的value值
        # 获取page的值，url内输入的?page = 页码数  显示你输入的页面数目 默认为第1页
        num = request.GET.get('page', 1)
        # 获取第几页
        number = page.page(1)
    except PageNotAnInteger:
        # 如果输入的页码数不是整数，那么显示第一页数据
        number = page.page(1)
    except EmptyPage:
        number = page.page(page.num_pages)

    start = int(num)  # 当前页面数

    if page_num > 5:  # 总分页数大于5
        if start + 5 > page_num:  # 你输入的值
            pageRange = range(start - 5, start)

        else:
            pageRange = range(start, start + 5)  # 显示分页按钮数量

    else:
        pageRange = page.page_range  # 正常分配range(1, 4)


    currentPage = page.page(num)  # 当前页面
    article_list = currentPage.object_list

    return render(request, 'blog/category.html', context=locals())

templates/blog/archive.html
{% extends "base.html" %}


{% block title %}
    <title>博客归档</title>
{% endblock %}

{% block css %}
    <link href="/static/css/archives.css" rel="stylesheet">
{% endblock %}




{% block content %}
    <section class="mysection main" style="animation: fuxiasuo 0.8s;">
        <ul class="timeline">

    <h5> 记录数:{{ article_list.count }} </h5>

            <hr/>


            {% for article in article_list %}

                <li>  {{ article.publish.date }}  <a href="{% url "blog:detail" pk=article.id%}">   <strong> {{ article.title|truncatechars:15 }}  </strong></a></li>
                <br/>




            {% endfor %}








    </section>
{% endblock %}



{##}
{##}
{##}
{#<div class="uk-container">#}
{##}
{#<ul>#}
{#     {% for article in article_list %}#}
{##}
{#        <li>{{ article.publish.year}}年#}
{##}
{#        {% regroup article_list by article.publish.month as posts_by_month %}#}
{#        <ul>#}
{#            {% for month in posts_by_month %}#}
{#                <li id="{{ year.grouper }}{{ month.grouper|stringformat:'02d' }}">{{ month.grouper }}月#}
{#                    <ul>#}
{#                        {% for post in month.list %}#}
{#                            <li>{{ article.publish.day}}日 <a href="{{ post.get_absolute_url }}" class="uk-link-reset uk-button-text">{{ post.title }}</a> </li>#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#        </li>#}
{#    {% endfor %}#}
{#</ul>#}
{#</div>#}
{##}
{##}
{##}
{#{% endblock %}#}

templates/blog/category.html
{% extends 'base.html' %}

{% block content %}


    <!-- 主体 -->
    <div class=" span8 l_box f_l ">

        <section>
            <div class="page-header">
                {#                    <h3>文章</h3>#}
            </div>
        </section>

        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% endif %}



        <!--列表开始-->
        <ul>
            {% for article in article_list %}
                <li>


                    <div class="article well clearfix ">
                        {#                        <section class="visible-md visible-lg">#}
                        <section class="new">
                            <div class="title-article">
                                <h4 class="blue-text text-center"><a href="{% url "blog:detail" pk=article.id %}"
                                                                     title="{{ article.title }}">{{ article.title }}</a>
                                </h4>

                                <div class="content-article text-center">
                                    <div class="alert alert-zan">     {{ article.digest }} ...</div>
                                </div>


                                <ul>


                                    <li class="glyphicon glyphicon-user"><i
                                            class="el-user"></i> {{ article.author.upper }} &nbsp
                                    </li>

                                    <li class="glyphicon glyphicon-time"><a
                                            href="/archive/{{ article.publish.year }}/{{ article.publish.month }}"
                                            title="发表于: {{ article.publish }}">
                                        <i class="el-time"></i>{{ article.publish.year }}年{{ article.publish.month }}月&nbsp</a>
                                    </li>


                                    {#                                    <li class="glyphicon glyphicon-pencil"> <a href="#" title="已有 {{ article.comment_set.all }} 条评论">#}
                                    {#                                        <i class="el-comment"> {{ article.comment }}条评论&nbsp</i></a></li>#}

                                    {#                                <li class="glyphicon glyphicon-eye-open"> <a title="已有 {{ article.view }} 次浏览">#}
                                    {#                                    <i class="el-eye-open"></i>{{ article.view }}</a></li>#}


                                    {#                                    {% for category in category_list %}#}
                                    {#                                        {{ category }}#}

                                    <li class="glyphicon glyphicon-th-list"><a
                                            href="{% url "blog:category" article.category.pk %} " title="分类"><i
                                            class="el-th-list"></i>{{ article.category }}</a></li>

                                    {#                                    {% endfor %}#}

                                </ul>
                            </div>

                        </section>

                    </div>

                </li>
            {% endfor %}



            {% if page.object_list %}
                <!--分页 -->
                <li>
                    <nav aria-label="Page navigation">
                        <ul class="pagination">


                            {% if currentPage.has_previous %}
                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ currentPage.previous_page_number }} "
                                       aria-label="Previous">
                                        <span aria-hidden="true">上一页</span>
                                    </a>
                                </li>
                            {% endif %}




                            {% for page_line  in  pageRange %}

                                {% if currentPage.number == page_line %}
                                    <li class="active"><a href="{% url "blog:category" cate.pk %}?page={{ page_line }} ">{{ page_line }} </a>
                                    </li>
                                {% else %}
                                    <li><a href="{% url "blog:category" cate.pk %}?page={{ page_line }} ">{{ page_line }} </a>
                                    </li>
                                {% endif %}

                                {#                                <li>#}
                                {#                                    <a href="{% url "blog:category" cate.pk %}?page={{ page_line }} ">{{ page_line }} </a>#}
                                {#                                </li>#}

                            {% endfor %}




                            {% if currentPage.has_next and currentPage.number > pageRange %}
                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ currentPage.next_page_number }} "
                                       aria-label="Next">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                                {#                            {% else %}#}
                                {#                                <li>#}
                                {#                                    <a href="{% url "blog:category" cate.pk %}?page={{ page_num }} " aria-label="Next">#}
                                {#                                        <span aria-hidden="true">末尾</span>#}
                                {#                                    </a>#}
                                {#                                </li>#}

                            {% endif %}


                        </ul>
                    </nav>

                </li>
            {% endif %}


        </ul>
        <!--列表结束-->


    </div>






    <!--=========右侧开始==========-->
    {% include "blog/right.html" %}
    <!--=========END右侧==========-->

{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}<title>{{ article.title }} -以谁为师的博客</title> {% endblock %}


{% block content %}

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">

                <div class="row-fluid">

                    <!-- 文章内容 -->
                    <div class="span8 l_box f_l">
                        <h3 class="text-center">
                            {{ article.title }}
                        </h3>
                        <p class="text-center">{{ article.publish.date }}&nbsp&sdot;
                            浏览量:&nbsp{{ article.view }}&nbsp&nbsp&nbsp

                            {% if user_login %}
                                <a href="/admin/blog/article/{{ article.pk }}/change/"
                                   class="glyphicon glyphicon-wrench"></a>
                            {% endif %}
                        </p>

                        <br/>
                        {{ article.body |safe }}
                    </div>


                    <!-- 右侧栏 -->
                    <div class="side">
                        <br/><br/>

                        {% if toc %}
                            <h4>
                                目录
                            </h4>

                            {{ toc|safe }}
                            <hr/>


                        {% endif %}



                        {##}
                        {##}
                        {#                            <h4 > 运维圈大本营QQ群:</h4>#}
                        {#                            <p> <font size="3" color="#FF0000">5501770161</font>  </p>#}
                        {#                            <br>#}
                        {##}
                        {#                            <img src="/media/home_page/yw.jpg" style="width:80%" class="img-rounded center-block">#}
                        {#                            <br/>#}
                        {#                            <br/>#}
                        {##}
                        {##}
                        {##}
                        {#                            <h2>#}
                        {#                                xxx#}
                        {#                            </h2>#}
                        {#                            <p>#}
                        {#                                本可视化布局#}
                        {#                            </p>#}
                        {#                            <p>#}
                        {#                                <a class="btn" href="#">github »</a> <a class="btn" href="#">xops.attacker.club »</a>#}
                        {#                            </p>#}


                        <!--标签-->
                        <div class="cloud bg-color animation-div">
                            <h4 class="index-title"><i class="el-tags"></i>标签
                                <small>Tags</small>
                            </h4>
                            <ul id="3dcloud">
                                {% for tag in detail_tag %}


                                    <li><a href="{% url "blog:tag" %}{{ tag }}" title="标签：{{ tag }} ">{{ tag }}</a></li>


                                {% endfor %}
                            </ul>
                        </div>

                        <hr/>
                        <h4>&nbsp&nbsp&nbsp&nbsp&nbsp扫码加入运维圈</h4>


                        <img src="/media/home_page/qq.png" style="width:60%">
                        <br/>
                        <br/>


                    </div>


                    <!-- 文尾声明 -->
                    <div class="div-left alert-success ">
                        <img src={% static 'img/pay.jpg' %} alt="微信打赏"/>
                        <p>作者： 以谁为师</p>
                        <p>最后更新： {{ article.mod_date }} </p>
                        <p> 原始链接： http://attacker.club{% url "blog:detail" pk=article.id %} </p>
                        <p> 转载本文请注明出处</p>
                    </div>


                    <!-- 底部评论 -->
                    <div class="row">
                        <div class="col-lg-8">
                            <hr/>
                            <br/>
                            <form action="{% url 'comments:article_comment' article.pk %}" method="post"
                                  class="comment-form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-3">
                                        <label for="{{ form.name.id_for_label }}">用户：</label>
                                        {{ form.name }}
                                        {{ form.name.errors }}
                                    </div>

                                    <div class="col-md-3">
                                        <label for="{{ form.email.id_for_label }}">Email：</label>
                                        {{ form.email }}
                                        {{ form.email.errors }}
                                    </div>

                                    <div class="col-md-3">
                                        <label for="{{ form.url.id_for_label }}">website：</label>
                                        {{ form.url }}
                                        {{ form.url.errors }}
                                    </div>


                                    <div class="col-md-12">
                                        {#                            <label for="{{ form.text.id_for_label }}">评论：</label>#}
                                        <br/>
                                        {{ form.text }}
                                        {{ form.text.errors }}
                                        <button type="submit" class="comment-btn">发表</button>
                                    </div>
                                </div>    <!-- row -->
                            </form>
                            <br/>

                            <ul class="comment-list list-unstyled">

                                <h3>留言区:</h3>
                                <hr/>


                                {% for comment in comment_list %}


                                    <li class="comment-item">

                                        <img src="/media/home_page/1.jpeg" style="width:5%">

                                        <span class="nickname">{{ forloop.counter }}楼 <strong> {{ comment.name }}  </strong></span>

                                        <time class="submit-date">&sdot;&nbsp{{ comment.created_time }}</time>

                                        {% if comment.url %}
                                            <a href="{{ comment.url }}" target="_blank">
                                                <span class="glyphicon glyphicon-link ">网站</span>
                                            </a>
                                        {% endif %}



                                        <div class="text">
                                            <br/>
                                            {{ comment.text }}
                                    </li>
                                    <hr/>
                                    {#    <p> 你的ip{{ ipaddr }} 你的客户端{{ ua }}</p>#}
                                {% empty %}
                                    暂无评论
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                </div>

            </div>

        </div>
    </div>




{% endblock %}

templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>用户输入：</h1>
    <form action="/login" method="post">
        {% csrf_token %}   <!--加入这行 -->
        <input type="text" name="username" />
        <input type="password" name="password" />
        <input type="submit" value="提交" />
    </form>
</body>
</html>