blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --------------------------------------------------
# Author:    LJ
# Email:     admin@attacker.club

# Date:      18-5-29
# Description:
# --------------------------------------------------


from django.urls import path, re_path, include
# re_path方法相当于 django1.11 url正则表达式
from . import views
from . import custom_search

# 载入视图模块

from haystack.views import SearchView

app_name = 'blog'
# 设置应用命名空间

urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.IndexView.as_view(), name="index"),

    # r正则;（）取出的内容;?P<> 里面是视图的参数名;[0-9]+数字;$结尾
    # re_path(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # re_path(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # re_path(r'^detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    re_path(r'^detail/(?P<pk>\d+).html$', views.detail, name='detail'),
    # re_path(r'^archive/$', views.archive, name='archive'),
    re_path(r'^articles/$', views.archive, name='articles'),
    # re_path(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archive, name='archive'),
    path('archive/<int:year>/<int:month>/', views.archive, name='archive'),  # http://127.0.0.1:8000/archive/2019/1/

    re_path(r'^tag/$', views.TagView.as_view(), name='tag'),
    re_path(r'^category/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^archive/$', views.ArchiveView.as_view(), name='archive'),
    # re_path(r'^search/$', views.search, name='search'),

    # path(r'search/', include('haystack.urls'),name='search'),
    # re_path(r'search/', , name='haystack_search'),

    # re_path(r'^search/',views.MySearchView, name='haystack_search'),

    # re_path('^search/', views.MySearchView.as_view(), name='haystack_search'),

    re_path('^search/', custom_search.MySearchIndex(), name='haystack_search'),

    re_path(r'^tag/(?P<name>.*?)/$', views.tag, name='tag'),
    re_path(r'^category/(?P<pk>\d+)/$', views.category, name='category'),

    # ex: /polls/5/
    # ex: /polls/5/results/
    # ex: /polls/5/vote/
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

from django.conf import settings

from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.shortcuts import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comments.urls')),
    path('', include('blog.urls',namespace='blog')), # 默认首页
    path('topic/', include('topic.urls',namespace='topic')), # 专题
    path('mdeditor/',include('mdeditor.urls')),
    # re_path(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /admin', content_type='text/plain')),

]

#http://127.0.0.1:8000/blog


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topic/urls.py
from django.urls import path, re_path, include
# re_path方法相当于 django1.11 url正则表达式
from . import views
# from . import custom_search

# 载入视图模块

from haystack.views import SearchView

app_name = 'topic'
# 设置应用命名空间

urlpatterns = [

    re_path('(?P<pk>\d+).html$', views.topic, name='part'),

    # path('', views.index, name="index"),
    # path('topic', views.IndexView.as_view(), name="index"),
    #
    #
    # # re_path(r'^detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    # re_path(r'^/topics/detail/(?P<pk>\d+).html$', views.detail, name='detail'),
    ]

blog/models.py
from django.db import models
from django.utils import timezone

from mdeditor.fields import MDTextField #

class Category(models.Model): #分类
    """
    继承django.db.models.Models模块
    """
    name = models.CharField(verbose_name='文章分类',max_length=100)

    class Meta:
        verbose_name_plural = "分类"
    def __str__(self):
        return self.name


class Tag(models.Model): #标签
    name = models.CharField(verbose_name='标签',max_length=100)

    class Meta:
        verbose_name_plural = "标签"
    def __str__(self):
        return self.name


class Article(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    django会自动新建自增id作为主键
    """

    status_choice = (
        (0, '原'),
        (1, '转'),
        (2, '顶'),
    )




    title = models.CharField(verbose_name='标题',max_length=70) # 标题
    body = MDTextField(verbose_name='正文',blank=True, null=True)
    #body = models.TextField(verbose_name='正文',blank=True, null=True)  # 文章正文
    digest = models.TextField(blank=True, null=True)  # 文章摘要
    status = models.SmallIntegerField(choices=status_choice, default=0, verbose_name='类型')
    publish = models.DateTimeField(verbose_name='发布时间',default=timezone.now) #发布时间
    mod_date = models.DateField(verbose_name='更新时间',auto_now=True) #更新时间

    category = models.ForeignKey(Category,verbose_name='分类', on_delete=models.CASCADE)
    #分类
    tags = models.ManyToManyField(Tag,verbose_name='标签', blank=True) #标签

    view = models.BigIntegerField(verbose_name='阅读数',default=0)  # 阅读数
    # comment = models.BigIntegerField(verbose_name='评论数',default=0)  # 评论数
    author = models.CharField(default='anonymous', verbose_name='作者', editable=False, max_length=128)
    picture = models.CharField(verbose_name='图片地址',max_length=200,blank=True,null=True) # 图片地址

    def __str__(self):
        return self.title


    def viewed(self):
        """
        增加阅读数
        :return:
        """
        self.view += 1
        self.save(update_fields=['view'])
    # def commenced(self):
    #     """
    #     增加评论数
    #     :return:
    #     """
    #     self.comment += 1
    #     self.save(update_fields=['comment'])

    def save(self, *args, **kwargs):
        """
        重写摘要
        :param args:
        :param kwargs:
        :return:
        """
        body = self.body

        # 从 body 摘取前 54 个字符赋给到 excerpt
        self.digest = body[:80]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Article, self).save(*args, **kwargs)


    class Meta:
        ordering = ['-publish']
        verbose_name_plural  = "文章"



#
# class Comment(models.Model):
#     title = models.CharField("标题", max_length=100)
#     source_id = models.CharField('文章id或source名称', max_length=25)
#     create_time = models.DateTimeField('评论时间', auto_now=True)
#     user_name = models.CharField('评论用户', max_length=25)
#     url = models.CharField('链接', max_length=100)
#     comment = models.CharField('评论内容', max_length=500)


class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name




"""
    digest = models.CharField(verbose_name='摘要',max_length=200, blank=True) # 文章摘要
    def save(self, *args, **kwargs): #复写 save 方法获取摘
        # 从 body 摘取前 54 个字符赋给到 digest
        self.digest = self.body[:54]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Article, self).save(*args, **kwargs)
"""

comments/models.py
from django.db import models

# Create your models here.



from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField('评论用户', max_length=50)
    email = models.EmailField('邮箱',max_length=255)
    url = models.URLField('站点', max_length=100,blank=True,)
    text = models.TextField('评论内容', max_length=500)
    created_time = models.DateTimeField('评论时间',auto_now_add=True)

    article = models.ForeignKey('blog.Article',on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.text[:20]

    def commenced(self):
        """
        增加评论数
        :return:
        """
        self.comment += 1
        self.save(update_fields=['comment'])

    class Meta:
        verbose_name_plural = "评论"

    def __str__(self):
        return self.name

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>

    {% block title %}<title>以谁为师的博客</title> {% endblock %}

    {% block meta %}
        <meta charset="UTF-8">
        <meta name="keywords" content="Python,运维开发,自动化,安全攻防以及极客技术分享的网站"/>
        <meta name="description" content="j_hao104的博客,一个个人网站，IT技术分享，记录IT生活，提供技术分享和作品分享的个人网站"/>
    {% endblock %}

    <meta name="360-site-verification" content="9ebe48d1a40d3e7407d190285b023ced" />
    <meta name="baidu-site-verification" content="djcP2ADLUf" />

    <meta name="author" content="Logos" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 移动设备缩放页面  "mete:vp"tab建 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <!-- 高速浏览器有最新的引擎渲染 "meta:compat" tab...-->
    <link rel="stylesheet" href="">
    <!-- "link" tab...  -->



    <link rel='icon' href="{% static  'img/g2.ico' %}" type='image/x-ico' >


    <!-- Bootstrap  CSS -->
{#   <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
   <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">


{##}
{#    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">#}

    <!-- Custom  CSS -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">


    <!-- Code CSS-->
{#   <link href="{% static 'css/code.css' %}" rel="stylesheet">#}
{#    <link type="text/css" rel="stylesheet" href={% static 'css/code.css' %} >#}
  <link rel="stylesheet" type="text/css" href="{% static 'css/code.css' %}">  {#语法高亮#}



{# 推送百度收录#}
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>


{# 访问统计#}
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?68c02012fb1ff8b162868bf6ce337c47";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>


</head>



<body>


<!--导航开始-->
{% include "header.html" %}
<!--导航结束-->

<!--主题框架开始-->
<div class="container">

    {% block content %}
    {% endblock %}

</div>
<!--主题框架结束-->

<!---底部开始-->
{% include "footer.html" %}
<!---底部结束-->

    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>



</body>

</html>

templates/category.html
{% extends 'base.html' %}

{% block content %}


    <!-- 主体 -->
    <div class=" span8 l_box f_l ">

        <section>
            <div class="page-header">
                {#                    <h3>文章</h3>#}
            </div>
        </section>

        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% endif %}



        <!--列表开始-->
        <ul>
            {% for article in article_list %}
                <li>


                    <div class="article well clearfix ">
                        {#                        <section class="visible-md visible-lg">#}
                        <section class="new">
                            <div class="title-article">
                                <h4 class="blue-text text-center"><a href="{% url "blog:detail" pk=article.id %}"
                                                                     title="{{ article.title }}">{{ article.title }}</a>
                                </h4>

                                <div class="content-article text-center">
                                    <div class="alert alert-zan">     {{ article.digest }} ...</div>
                                </div>


                                <ul>


                                    <li class="glyphicon glyphicon-user"><i
                                            class="el-user"></i> {{ article.author.upper }} &nbsp
                                    </li>

                                    <li class="glyphicon glyphicon-time"><a
                                            href="/archive/{{ article.publish.year }}/{{ article.publish.month }}"
                                            title="发表于: {{ article.publish }}">
                                        <i class="el-time"></i>{{ article.publish.year }}年{{ article.publish.month }}月&nbsp</a>
                                    </li>


                                    {#                                    <li class="glyphicon glyphicon-pencil"> <a href="#" title="已有 {{ article.comment_set.all }} 条评论">#}
                                    {#                                        <i class="el-comment"> {{ article.comment }}条评论&nbsp</i></a></li>#}

                                    {#                                <li class="glyphicon glyphicon-eye-open"> <a title="已有 {{ article.view }} 次浏览">#}
                                    {#                                    <i class="el-eye-open"></i>{{ article.view }}</a></li>#}


                                    {#                                    {% for category in category_list %}#}
                                    {#                                        {{ category }}#}

                                    <li class="glyphicon glyphicon-th-list"><a
                                            href="{% url "blog:category" article.category.pk %} " title="分类"><i
                                            class="el-th-list"></i>{{ article.category }}</a></li>

                                    {#                                    {% endfor %}#}

                                </ul>
                            </div>

                        </section>

                    </div>

                </li>
            {% endfor %}



            {% if page.object_list %}
                <!--分页 -->
                <li>
                    <nav aria-label="Page navigation">
                        <ul class="pagination">


                            {% if currentPage.has_previous %}
                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ currentPage.previous_page_number }} "  aria-label="Previous">
                                        <span aria-hidden="true">上一页</span>
                                    </a>
                                </li>
                            {% endif %}




                            {% for page_line  in  pageRange %}

                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ page_line }} ">{{ page_line }} </a>
                                </li>

                            {% endfor %}




                          {% if currentPage.has_next %}
                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ currentPage.next_page_number }} "
                                       aria-label="Next">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url "blog:category" cate.pk %}?page={{ page_num }} " aria-label="Next">
                                        <span aria-hidden="true">末尾</span>
                                    </a>
                                </li>

                            {% endif %}



                        </ul>
                    </nav>

                </li>
            {% endif %}


        </ul>
        <!--列表结束-->


    </div>






    <!--=========右侧开始==========-->
    {% include "right.html" %}
    <!--=========END右侧==========-->

{% endblock %}

templates/footer.html
<footer>
    <br/>
    <div class="foot-nav navbar-fixed-boottome">
        <div class="text-center">
            <span>CopyRight &#169;{% now " Y " %}  &#160;<a href="http://attacker.club">以谁为师</a>&#160;&#160;Powered by Django2</span>

        </div>
    </div>
    <br/>
</footer>

templates/header.html
<div class="container-fluid">
    <!--导航开始-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <!--navbar-inverse 黑色背景导航栏,navbar-fixed-top 导航栏固定到顶部 -->

        {% if not user_login %}
            <div class="nav navbar-nav div-right hidden-xs">
                <ul class="nav navbar-nav">
                    <li><a href="/admin"><span class=" glyphicon glyphicon-log-in"></span> 登录</a></li>
                </ul>
            </div>

        {% else %}

            <div class="nav navbar-nav div-right hidden-xs">
                <ul class="nav navbar-nav">
                    <li><a href="/admin/blog/article/add/"><span class="glyphicon glyphicon-pencil"></span> 发布</a></li>
                </ul>
            </div>

        {% endif %}


        <div class="container">
            <!-- 放入logo-->
            <!--  <a href="http://attacker.club" class="navbar-brand"><strong>Attacker.club</strong></a> -->


            <!-- 登陆&注册栏
{#    <div class="navbar-right  hidden-xs">#}
{#        <ul class="nav navbar-nav">#}
{#            <a class="login btn btn-normal btn-primary" href="http://www.attacker.club/?/account/login/">登录</a>#}
{#            <a class="register btn btn-normal btn-success" href="http://www.attacker.club/?/account/register/">注册</a>#}
{#    </ul>#}
</div>-->

            {#            <div class="nav navbar-nav  div-right  hidden-xs">#}
            {#                <ul class="nav navbar-nav">#}
            {#                    <a class="login btn btn-normal btn-primary " href="http://www.attacker.club/?/account/login/">登录</a>#}
            {#                </ul>#}
            {#            </div>#}


            {#            http://127.0.0.1:8000/admin/blog/article/add/#}


            <!--折叠 响应式导航栏 -->
            <div class="navbar-header navbar-left">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-navbar">
                    <span class="icon-bar">  </span>
                    <span class="icon-bar">  </span>
                    <span class="icon-bar">  </span>
                </button>
            </div>


            <div class="collapse navbar-collapse" id="responsive-navbar">

                <!--菜单栏 -->
                <ul class="nav navbar-nav">

                    <li class="ative"><a href="/"> 主页 </a></li>


                    <li><a href="{% url "blog:category" %}3"> Python </a></li>

                    <li><a href="{% url "blog:category" %}1">前端设计 </a></li>

                    <li><a href="{% url "blog:category" %}2"> Web开发 </a></li>

                    <li><a href="{% url "blog:category" %}4"> 安全攻防 </a></li>

                    {#                    <li><a href="{% url "blog:category"%}4"> 数据库 </a> </li>#}

{#                    <li><a href="{% url "blog:category" %}15"> 数据应用 </a></li>#}

                    {#                    <li><a href="#"> 智能家居 </a> </li>#}
                    {#                    <li><a href="#"> 博彩娱乐 </a> </li>#}

                    {#                    <li><a href="{% url "blog:archive" %}"> 时间归档 </a></li>#}


                    

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">技术专题<b class="caret"></b></a>
                        <ul class="dropdown-menu">


                            {% for k,v in topic_indexes.items %}

                                <li><a href="{% url "topic:part" k %}"> {{ v }} </a></li>

                            {% endfor %}



                        </ul>
                    </li>


                </ul>


                <!-- 添加搜索表单 -->
                {#                <form action="{% url 'blog:search' %}"  method="get"  class="navbar-form  pull-right  ">#}
                <form action="{% url 'blog:haystack_search' %}" method="get" class="navbar-form  pull-right  ">

                    {#                    <input type="search" name='key' placeholder="搜索 ... "  class="form-control ">#}
                    <input type="search" name='q' placeholder="搜索 ... " class="form-control ">

                    <button type="submit">
                        <span class="glyphicon glyphicon-search "></span>

                        <!-- form-control 可以额外添加样式
                        glyphicon 小图标;button 按钮

                        https://getbootstrap.com/docs/3.3/components/-->
                    </button>
                </form>

                {#                <form role="search" method="get" id="searchform" action="{% url 'blog:haystack_search' %}">#}
                {#                    <input type="search" name="q" placeholder="搜索" required>#}
                {#                    <button type="submit"><span class="ion-ios-search-strong"></span></button>#}
                {#                </form>#}


            </div>
        </div>
    </nav>
    <!--导航结束-->
</div>

templates/index.html
{% extends 'base.html' %}

{% block content %}


    <!-- 主体 -->
    <div class=" span8 l_box f_l ">


        <section>
            <div class="page-header">
                {#                    <h3>文章</h3>#}
            </div>
        </section>

        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% endif %}



        <!--列表开始-->
        <ul>
            {% for article in article_list %}
                <li>


                    <div class="article well clearfix ">
                        <section class="new">
                            <div class="title-article">
                                <h4 class="blue-text text-center"><a href="{% url "blog:detail" pk=article.id %}"
                                                                     title="{{ article.title }}">{{ article.title }}</a>

                                     <li   class="btn btn-success btn-xs  ">{{ article.get_status_display }}</li>
                                </h4>



                                <div class="content-article text-center">
                                    <div class="alert alert-zan">     {{ article.digest }} ...</div>
                                </div>


                                <ul>


                                    <li class="glyphicon glyphicon-user"><i
                                            class="el-user"></i>
{#                                        {{ article.author.upper }}#}
                                        admin&nbsp;
                                    </li>

                                    <li class="glyphicon glyphicon-time"><a
                                            href="/archive/{{ article.publish.year }}/{{ article.publish.month }}"
                                            title="发表于: {{ article.publish }}">
                                        <i class="el-time"></i>{{ article.publish.year }}年{{ article.publish.month }}月&nbsp;</a>
                                    </li>


                                    {#                                    <li class="glyphicon glyphicon-pencil"> <a href="#" title="已有 {{ article.comment_set.all }} 条评论">#}
                                    {#                                        <i class="el-comment"> {{ article.comment }}条评论&nbsp</i></a></li>#}

                                    {#                                <li class="glyphicon glyphicon-eye-open"> <a title="已有 {{ article.view }} 次浏览">#}
                                    {#                                    <i class="el-eye-open"></i>{{ article.view }}</a></li>#}


                                    {#                                    {% for category in category_list %}#}
                                    {#                                        {{ category }}#}

                                    <li class="glyphicon glyphicon-th-list"><a
                                            href="{% url "blog:category" article.category.pk %} " title="分类"><i
                                            class="el-th-list"></i>{{ article.category }}</a></li>

                                </ul>

                            </div>

                        </section>

                    </div>

                </li>
            {% endfor %}



            {% if page %}
                <!--分页 -->
                <li>
                    <nav aria-label="Page navigation">
                        <ul class="pagination">

                            {#                             <li role="presentation" class="active"><a href="{% url "blog:index" %}">Home</a></li>#}


                            {% if currentPage.has_previous %}
                                <li>
                                    <a href="{% url "blog:index" %}?page={{ currentPage.previous_page_number }} "
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}

                                                        {% if currentPage.number > 2 %}
                                                            <li>
                                                                <a href="{% url "blog:index" %}?page=1" aria-label="Home">
                                                                    <span aria-hidden="true">1</span>
                                                                </a>
                                                            </li>
                                                        {% endif %}

{#                                                      {% if currentPage.number > 3 %}#}
{#                                                            <li>#}
{#                                                                <a href="{% url "blog:index" %}?page={{ page_num }}" aria-label="Home">#}
{#                                                                    <span aria-hidden="true">1</span>#}
{#                                                                </a>#}
{#                                                            </li>#}
{#                                                        {% endif %}#}



                            {% for page_line  in  pageRange %}
                                {% if currentPage.number == page_line %}
                                    <li class="active"><a
                                            href="{% url "blog:index" %}?page={{ page_line }} ">{{ page_line }} </a>
                                    </li>
                                {% else %}
                                    <li><a href="{% url "blog:index" %}?page={{ page_line }} ">{{ page_line }} </a></li>
                                {% endif %}

                            {% endfor %}

                            {#                                                        <li>...</li>#}


                            {#                            {% if currentPage.has_next #}
                            {% if currentPage.has_next%}

                                <li><a>... </a></li>


                                {% if page_num > 6 and currentRange < page_num %}
                                    <li>
                                        <a href="{% url "blog:index" %}?page={{ page_num }}" aria-label="End">
                                            <span aria-hidden="true">{{ page_num }}</span>
                                        </a>
                                    </li>
                                {% endif %}


                                <li>
                                    <a href="{% url "blog:index" %}?page={{ currentPage.next_page_number }}"
                                       aria-label="Next">
                                        <span aria-hidden="true"> &raquo;</span>
                                    </a>
                                </li>
{#                            {% else %}#}
{#                                <li>#}
{#                                    <a href="{% url "blog:index" %}?page={{ page_num }} " aria-label="Next">#}
{#                                        <span aria-hidden="true">末尾</span>#}
{#                                    </a>#}
{#                                </li>#}
                            {% endif %}


                        </ul>


                    </nav>


                </li>
            {% endif %}


        </ul>
        <!--列表结束-->


    </div>

    {##}
    {#    {% for page in page.object_list %}#}
    {#        {{ forloop.counter }}#}
    {#    {% endfor %}#}
    {##}
    {#    {{ page_first }} {{ page_first.object_list }}#}
    {#    {{ page_first.count }}#}
    {#     {% for i in pageRange %}#}
    {#         {% if current_num == i %}#}
    {#          <li class="active"><a href="?page={{ i }}">{{ i }}</a></li>#}
    {##}
    {#         {% else %}#}
    {#          <li><a href="?page={{ i }}">{{ i }}</a></li>#}
    {#         {% endif %}#}
    {#    {% endfor %}#}




    <!--=========右侧开始==========-->
    {% include "blog/right.html" %}
    <!--=========END右侧==========-->

{% endblock %}

templates/links.html
<!--友情链接-->
<div class="side-link animation-div">
    <h4 class="index-title"><i class="el-paper-clip"></i>友情链接
        <small>Friend Links</small>
        <a href="mailto:admin@attacker.club?subject=博客友链互换&body=博客名称: xxx   博客地址: xxx  博客描述: xxx"><i class="el el-plus"></i>申请</a></h4>
    <ul>

        <li><a href="https://www.waitalone.cn/" target="_blank" title="信息安全">独自等待</a></li>
        <li><a href="http://www.cnblogs.com/richardzgt" target="_blank"  title="运维技术">高涛博客园</a></li>
        <li><a href="https://looaon.com" target="_blank" title="技术,生活">渗透-冬哥</a></li>
        <li><a href="https://blog.nbhao.org/" target="_blank" title="运维技术">章郎虫博客</a></li>
        <li><a href="https://tool.lu" target="_blank" title="在线工具,开发人员工具,代码格式化、压缩、加密、解密,下载链接转换,sql工具,正则测试工具...">程序员的工具箱</a></li>



</div>

templates/right.html
<!-- 侧边栏 -->
<div class="side ">



    <section>
        <div class="page-header">
            {#                    <h3>侧边栏</h3>#}
        </div>
    </section>




    <div class="sources">
        <div id="sources">
            <div class="sources">
                <div class="sources row">





                    <div class="span3">

                      <h4> 扫码加入运维圈</h4>
{#                        <p> <font size="3" color="#FF0000">5501770161</font>  </p>#}

                        <img src="/media/home_page/qq.png" style="width:50%">
                        <br/>
                        <br/>






                        <!--标签-->
                        <div class="cloud bg-color animation-div">
                            <h4 class="index-title"><i class="el-tags"></i>标签云
                                <small>Tags Clouds</small>
                            </h4>
                            <ul id="3dcloud">
                                {% for tag in tag_all %}


                                    <li><a href="{% url "blog:tag" %}{{ tag }}" title="标签：{{ tag }} ">{{ tag }}</a></li>


                                {% endfor %}
                            </ul>
                        </div>




                    </div>


                    <!--友情链接-->
                    {% include "links.html" %}



                </div>
            </div>

        </div>
    </div>

</div>